### ISSUE TITLE
drivers/cc3xx: cc310 gets stuck on first operation after SW reset

### ISSUE THREAD

**Issue by mguetschow** [TrustedFirmware-M/trusted-firmware-m#12]
While testing the low-level driver cc3xx for the CRYPTOCELL peripheral in the nRF52840 (which uses a cc310), I noticed that the driver gets stuck after the first write to OPCODE since PKA_DONE would never return 1.

Apparently, triggering the software reset with SW_RESET takes some time and the subsequent initialization is therefore not carried out correctly.

Fix proposed in https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/31743

**Comment by adeaarm** [comment]
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/31718 cherry-picked on `release/2.1.x`
