### ISSUE TITLE
Some integrations require ABI compatibility between external and internal interfaces

### ISSUE THREAD

**Issue by tomi-font** [TrustedFirmware-M/trusted-firmware-m#13]
Some checks added for 2.1.1 around size of `psa_key_attributes_t` parameters passed from the NS side get triggered in integrations that enforce ABI compatibility between external and internal interfaces.

For those, it is necessary to have a way to modify those checks to take into account this possibility.

**Comment by adeaarm** [comment]
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/31725
