### ISSUE TITLE
Pickup Mbed TLS 3.6.2

### ISSUE THREAD

**Issue by adeaarm** [TrustedFirmware-M/trusted-firmware-m#14]
Mbed TLS project has released version 3.6.2 on the LTS branch. Align TF-M to that as well.

**Comment by adeaarm** [comment]
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/32888

**Comment by nicola-mazzucato-arm** [comment]
change from the release branch: https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/31726
