### ISSUE TITLE
STM32U5 bug on LTS TF-M 2.1.0

### ISSUE THREAD

**Issue by ahmadstm** [TrustedFirmware-M/trusted-firmware-m#2]
Hello,

There's issue on the LTS branch on the TF-M 2.1.0 on b_u585i_iot02a board, and this is the commit to resolve 
the problem: https://github.com/TrustedFirmware-M/trusted-firmware-m/commit/51eb66c726110408a7c8af787b46bbced23d1e3a 
this commit has been merged on main branch but not on LTS TF-M 2.1.0.
So, what should I do to this commit will be merged on the LTS TF-M 2.1.0?

Thanks,
Ahmad.

**Comment by adeaarm** [comment]
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/29600 is ready to be merged on `release/2.1.x`
