### ISSUE TITLE
Missing length check of input/output buffers in crypto partition

### ISSUE THREAD

**Issue by hunkob** [TrustedFirmware-M/trusted-firmware-m#4]
# 02: Missing length check of input/output buffers in crypto partition

## Summary

Similar to the missing checks on the number of input and output arguments (Report #01), the buffer length of many input/output vectors are not checked. This leads to potentially too small buffers to be written to in the SPE. These checks are missing in multiple locations of crypto message processing.

- **Impact:** Buffer out-of-bounds read/write in SPE
- **Severity:** High

## Technical Description

**Note:** See also *Technical Description* in Report #01.

Message dispatching of the crypto partition is implemented in [`secure_fw/partitions/crypto/crypto_init.c`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c):

- [`tfm_crypto_call_srv`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#190)
  - `in_vec[0]` is read and length is verified to be `sizeof(struct tfm_crypto_pack_iovec)`:
    - [`crypto_init.c:213`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#213)
    - [`crypto_init.c:218`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#218)
    - **Recommendation:** Replace `sizeof(struct tfm_crypto_pack_iovec)` with `sizeof(iov)` in [crypto_init.c:219](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#219)
  - no further checks on other `in_vec`/`out_vec` lengths (e.g. `out_vec[0].len`)

- [`tfm_crypto_api_dispatcher`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#334)
  - redundant check of `in_vec[0].len` in [`crypto_init.c:346`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#346)
  - no further checks on other `in_vec`/`out_vec` lengths (e.g. `out_vec[0].len`)
    - => many child functions miss checks for `in_vec`/`out_vec` lengths, e.g. `tfm_crypto_key_management_interface`
    - => **please check all child functions**
- example of missing checks in [`tfm_crypto_key_management_interface`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c#26) in [`secure_fw/partitions/crypto/crypto_key_management.c`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c)
  - usages of vector without length check (no access to `xxx_vec[x].len` in code):
    - `in_vec[1].base`:
      - https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c#39
      - https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c#141
      - https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c#167
    - `out_vec[1].base`:
      - https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c#43
      - https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c#62
      - https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c#81
      - https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c#93
      - https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c#143
  - please also verify size is correctly checked in places where `xxx_vec[x].len` is accessed

## Proposed fix

Overhaul the argument verification and remove implicit and undocumented assumptions of arguments lengths:

1. All child functions of [`tfm_crypto_api_dispatcher`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#334), such as [`tfm_crypto_key_management_interface`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c#26), should verify the correct length (`xxx_vec[x].len`) of each `xxx_vec[x]` prior to usage of `xxx_vec[x].base` and return an error if `len` is insufficient.
   Only `in_vec[0]` seems to be sufficiently checked in all circumstances

**Note:** See Issue #01 before working on a fix.

## Reproducer

For example a `TFM_CRYPTO_OPEN_KEY` message with `out_vec[0].len < 4` will write out-of-bounds:

```
mailbox_dispatch: CALL handle = 5e770140, type = 00000000
tfm_crypto_api_dispatcher: in_vec = 0800a890, in_len = 1, out_vec = 0800a8b0, out_len = 3

group_id = 01 (TFM_CRYPTO_GROUP_ID_KEY_MANAGEMENT), function_id = 0201 (TFM_CRYPTO_OPEN_KEY)

in_vec[0]: base = 0800a8d0, len = 48
[0800a8d0]  fd ff ff ff  ff ff ff 01  |....  ....|
[0800a8d8]  71 3c 34 80  00 00 00 00  |q<4.  ....|
[0800a8e0]  2c 28 b1 ec  00 00 00 00  |,(..  ....|
[0800a8e8]  00 00 00 00  00 00 00 20  |....  ... |
[0800a8f0]  00 00 00 00  03 03 03 03  |....  ....|
[0800a8f8]  00 00 00 00  01 02 02 02  |....  ....|
out_vec[0]: base = 0800aa08, len = 0
out_vec[1]: base = 0800aa08, len = 0
out_vec[2]: base = 0800aa08, len = 1
[0800aa08]  00                        |.         |
```

This leads to a 4-byte out-of-bounds write, excert from `frametrace-full-1838465.log`:

```
├─ RAM Access (Write) [ pc: 100012a6 (tfm_crypto_key_management_interface), size: 4, address: 0800aa08 (scratch), value: 00000000 ]
```

`100012a6` corresponds to [`secure_fw/partitions/crypto/crypto_key_management.c:184`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_key_management.c#184) which is an 4-byte write to `out_vec[0].base` write 4-bytes out-of-bound (`out_vec[0].len` is `0`).

**Note:** Writes to other parts of the SPE can be crafted using these OOB-write bugs. For example an malicous actor can combine this bug with Issue #03 to write to arbitrary addresses.

## Attachments

- [crash.log](https://github.com/user-attachments/files/16248086/crash.log): log file of oob-write input(s) (including sent message), see end of log
- [frametrace-1838465.log](https://github.com/user-attachments/files/16248087/frametrace-1838465.log): trace of all called function + context of crash

**Comment by adeaarm** [comment]
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/31298/1
