### ISSUE TITLE
Integer Overflow in allocation size check in `tfm_crypto_alloc_scratch`

### ISSUE THREAD

**Issue by hunkob** [TrustedFirmware-M/trusted-firmware-m#5]
# 03: Integer Overflow in allocation size check in `tfm_crypto_alloc_scratch`

## Summary

When serving incoming requests to the crypto partition, the partition logic allocates scratch buffers for the input and output argument vectors. To ensure proper alignment, the logic in `tfm_crypto_alloc_scratch` aligns the requested size upward to a 4-byte alignment. However, this alignment mechanism does not account for the edge case of an integer overflow for a user-provided `size >= 0xfffffffd`. For these values, the alignment process will "round up" to an allocation size of `0`, while the size indicated to the handler function is still the very large value `0xffffffff`. 

- **Impact:** ~~Buffer out-of-bounds read/write in SPE~~ None 
- **Severity:** ~~Critical~~ Low

## Technical Description

Message handling in [`secure_fw/partitions/crypto/crypto_init.c`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c):

- [`tfm_crypto_call_srv`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#190)
  - `in/out_vec` is allocated on a scratch buffer with `tfm_crypto_init_iovecs`

- [`tfm_crypto_init_iovecs`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#149)
  - allocates scratch buffer for `in_vec[i].base` and `out_vec[i].base` with `tfm_crypto_alloc_scratch`
  - sets the `in_vec[i].len` and `out_vec[i].len` to the corresponding `msg->xxx_size[i]` (without alignment)
- [`tfm_crypto_alloc_scratch`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#113)
  - aligns the `requested_size` to a multiply of [`TFM_CRYPTO_IOVEC_ALIGNMENT`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#44) (`4`) using [`ALIGN`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#38)
  - => this boils down to `requested_size = (requested_size + 3) & 0xfffffffc;` which can overflow to `0` for `requested_size >= 0xfffffffd`
  - => therefore the size may be set to `0xfffffffd` while the backing allocation is a `0`-byte buffer, creating a large OOB-read/write

## Proposed fix

In [`tfm_crypto_alloc_scratch`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/partitions/crypto/crypto_init.c#113):

- return an error if alignment of `requested_size` would overflow or
- return an error if `requested_size` is unreasonably large (e.g. `>= 0x80000000`)

## Reproducer

Due to [memory checks](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/spm/core/psa_call_api.c#110) in [`spm_associate_call_params`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/+/refs/tags/TF-Mv2.0.0/secure_fw/spm/core/psa_call_api.c#21) this bug can currently not be triggered from non-secure firmware.

## Attachments

- None

**Comment by adeaarm** [comment]
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/31297/1
