### ISSUE TITLE
[STM] Add helper script to simplify the build process on STM platoforms

### ISSUE THREAD

**Issue by ahmadstm** [TrustedFirmware-M/trusted-firmware-m#7]
Hello, 

I pushed this commit: https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/30057/5..6
to the main branch, I would like to merge it to LTS 2.1.0 to please.

Best regards,
AhmadSTM.

**Comment by adeaarm** [comment]
Cherry pick commit on the release/2.1.x branch is available here: https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/30457
